### ISSUE TITLE
Kernel hacking (?)

### ISSUE THREAD

**Issue by memegauste** [andi34/samsung_espresso_kernel#1]
https://github.com/meefik/linuxdeploy/issues/835
I suggest you to fix this bug in kernel if you can or port linux, since framebuffer supports it. 
It would be very exciting :)

**Comment by memegauste** [comment]
Ah and I though this is p5110 kernel, sorry.

**Comment by andi34** [comment]
Stock Samsung source only, no one will ever work on that source again
